diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
credential.http://172.16.15.49:8929.provider=generic
user.name=Abhishek-cipl
user.email=145000189+Abhishek-cipl@users.noreply.github.com
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
credential.http://54.179.198.212:8929.provider=generic
core.editor="C:\Users\Abhishek\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
gui.recentrepo=C:/Users/Abhishek/food-jagat-backend
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/AbhiGiri/foodjagat-backend.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
